### ISSUE TITLE
Better support for ES6 / Babel syntax

### ISSUE THREAD

**Issue by WickyNilliams** [SublimeText/Spacegray#150] opened 2015-02-24 12:38 UTC
If you set syntax to Babel (via [babel-sublime](https://github.com/babel/babel-sublime)), the theme gets a bit carried away and colours _almost everything_ in.

Here is spacegray (80s) set to JS syntax. Consider this our baseline:
![screen shot 2015-02-24 at 12 34 39](https://cloud.githubusercontent.com/assets/1091390/6349368/98a5cd26-bc21-11e4-8fe0-10c389e663bf.png)

Here is spacegray (80s) set to Babel syntax. As you can see, it seems to colourise far too much of the syntax, making it hard to quickly distinguish parts of the code:
![screen shot 2015-02-24 at 12 32 22](https://cloud.githubusercontent.com/assets/1091390/6349345/6afbec02-bc21-11e4-8c65-bd6b632318de.png)

Compare this with the Monokai variant that comes with babel-sublime. Much less colourised syntax, meaning easier to scan:
![screen shot 2015-02-24 at 12 32 55](https://cloud.githubusercontent.com/assets/1091390/6349346/6b022a0e-bc21-11e4-85c0-0f38e505a53a.png)

**Comment by jakemmarsh** [comment] 2015-05-27 06:25
+1. Love this theme more than any other I've found, but this could be a dealbreaker

**Comment by elaijuh** [comment] 2015-06-28 16:23
+1. really need this coming along with babel-sublime

**Comment by XemsDoom** [comment] 2015-07-02 07:32
+1 with the new syntax highlightning in Build 3094 Spacegray now per default will have the ugly highlightning.

![image](https://cloud.githubusercontent.com/assets/1385611/8471941/3e194c3a-209d-11e5-9ca2-b908241e1960.png)

**Comment by elaijuh** [comment] 2015-07-20 13:59
may i know if es2015 syntax will be supported? any time box for it?

**Comment by gaearon** [comment] 2015-07-27 18:02
I use Spacegray with Babel + Oceanic Next as color scheme.

**Comment by DenisIzmaylov** [comment] 2015-07-27 21:59
I use [my custom schema](https://github.com/DenisIzmaylov/webstorm-twilight2-theme)

**Comment by n1ghtmare** [comment] 2015-09-07 16:48
:+1:

**Comment by jsynowiec** [comment] 2015-11-15 20:29
+1. Would be nice to have a proper syntax highlighting for ES2015 and React in base16-eighties theme.

**Comment by mrchief** [comment] 2016-02-02 21:19
:+1: Please make the bleeding stop! :)

**Comment by deathaxe** [comment] 2024-08-31 09:59
Closing as duplicate of #167

**Closed by deathaxe** 2024-08-31 09:59 UTC
