### ISSUE TITLE
"Find" locates 4 matches, but is unable to scroll to them.

### ISSUE THREAD

**Issue by StefanHagen** [SublimeText/Spacegray#97] opened 2014-03-04 13:03 UTC
My issue is with the find function on the mac. Before installing the theme I could find al the matches of a string and flip through the document. Now when I search a document which for example has 4 matches it displays "4 matches, unable to find matches" in the left-hand bottom corner. It encircles the matches as I scroll through the document, but I used to be able to just hit Enter multiple times to flip through the matches and sublime would scroll through the document to display. Besides that, I think you did an awesome job on the UI!

**Comment by deathaxe** [comment] 2024-08-31 09:04
Can't reproduce. A theme affecting how search functionality works seems rather unlikely. Maybe it was a ST bug, which is now fixed.

**Closed by deathaxe** 2024-08-31 09:04 UTC
